"""empty message

Revision ID: 61b7719bcf37
Revises: 914505e508e6
Create Date: 2021-03-12 01:19:58.567432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b7719bcf37'
down_revision = '914505e508e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
