"""init db

Revision ID: f29ae2b3b150
Revises: 80f1b344aeb1
Create Date: 2021-02-16 16:49:47.834302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29ae2b3b150'
down_revision = '80f1b344aeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'message_user', ['message_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'message_user_id')
    # ### end Alembic commands ###
